# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1Nvf4it-Zyg7PUUfj2Wh4wphwrw2p6j
"""

!pip install -q gitpython google-generativeai

import os
import git
import google.generativeai as genai

# ------------------------------
# 1. Setup Gemini API Key
# ------------------------------
# 👉 Replace with your actual Gemini API key from Google AI Studio
genai.configure(api_key="")

# ------------------------------
# 2. Clone & Extract Repository Data
# ------------------------------
def clone_and_extract(repo_url, max_commits=50):
    repo_name = repo_url.split("/")[-1].replace(".git", "")
    if not os.path.exists(repo_name):
        git.Repo.clone_from(repo_url, repo_name)
    repo = git.Repo(repo_name)

    commits = []
    for i, commit in enumerate(repo.iter_commits()):
        if i >= max_commits: break
        commits.append(commit.message.strip())
    return commits

repo_url = "https://github.com/tensorflow/tensorflow.git"
commit_messages = clone_and_extract(repo_url)

print(f"✅ Collected {len(commit_messages)} commit messages")

# ------------------------------
# 3. Summarize Using Gemini LLM
# ------------------------------
def summarize_repo(messages):
    text = "\n".join(messages[:100])  # take first 100 commit messages for demo
    prompt = f"""
    You are RepoMind, an AI assistant. Summarize the following GitHub commit history
    in simple technical English. Highlight the main features and note project activity:

    {text}
    """
    # Use a correct Gemini model name
    model = genai.GenerativeModel("gemini-1.5-flash")  # fast + free tier
    response = model.generate_content(prompt)
    return response.text

summary = summarize_repo(commit_messages)

print("\n📌 Repository AI Summary (Gemini):\n")
print(summary)